apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      type: string
      description: "URL of the repository to clone."
    - name: branch
      type: string
      description: "Branch to checkout and use."
  tasks:
    - name: clone
      workspaces:
        - name: output  # Adjusted to 'output' based on the earlier task definition
          workspace: pipeline-workspace
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: revision
          value: "$(params.branch)"
        - name: deleteExisting
          value: "true"
    - name: lint
      workspaces:
        - name: source  # This task uses the 'source' workspace
          workspace: pipeline-workspace
      taskRef:
        name: flake8
      runAfter:
        - clone
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value:
            - "--count"
            - "--max-complexity=10"
            - "--max-line-length=127"
            - "--statistics"
    - name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: nose
      runAfter:
        - clone
      params:
        - name: database_uri
          value: "sqlite:///test.db"
        - name: args
          value: "-v --with-spec --spec-color"
