apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      type: string
      description: "URL of the repository to clone."
    - name: branch
      type: string
      description: "Branch to checkout and use."
  tasks:
    - name: clone
      workspaces:
        - name: output  # Assuming 'git-clone' expects an 'output' workspace based on error logs
          workspace: pipeline-workspace
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: revision
          value: "$(params.branch)"
        - name: deleteExisting
          value: "true"
    - name: lint
      workspaces:
        - name: source  # Assuming 'flake8' expects a 'source' workspace; adjust if needed
          workspace: pipeline-workspace
      taskRef:
        name: flake8
      runAfter:
        - clone
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value:
            - "--count"
            - "--max-complexity=10"
            - "--max-line-length=127"
            - "--statistics"
